main/urls.py
from django.urls import path, re_path

from main import views

app_name = 'main'
urlpatterns = [
    path('', views.main, name='main')
    # re_path('^.*', views.main, name='main')
]

shop/urls.py
<<<<<<< HEAD
"""shop URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
    # path('main/', include('main.urls')),
    path('', include('main.urls')),

    # re_path('^.*', include('main.urls'))
]
=======
"""shop URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
    path('userAuth/', include('userAuth.urls')),
    # path('main/', include('main.urls')),
    path('', include('main.urls')),

    # re_path('^.*', include('main.urls'))
]
>>>>>>> 2c0e25ea74f3e590d8571b3310da09d326f30201

store/urls.py
from django.urls import path

from store import views


app_name = 'store'
urlpatterns = [
    path('category/', views.category, name='category'),
    path('categoryCreate/', views.categoryCreate, name='categoryCreate'),
    path('categoryRead/<int:id>/', views.categoryRead, name='categoryRead'),
    path('categoryUpdate/<int:id>/', views.categoryUpdate, name='categoryUpdate'),
    path('categoryDelete/<int:id>/', views.categoryDelete, name='categoryDelete'),

    path('itemCreate/', views.itemCreate, name='itemCreate'),
    path('itemRead/<int:id>/', views.itemRead, name='itemRead'),

]

store/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Item(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.TextField()
    price = models.IntegerField()

    def __str__(self):
        return self.name

store/forms.py
from django import forms

from store.models import Category, Item


class CategoryForm(forms.ModelForm):
    name = forms.CharField(label='名稱', required=True)

    class Meta:
        model = Category
        fields = ('name', )


class ItemForm(forms.ModelForm):
    name = forms.CharField(label='名稱', widget=forms.TextInput(attrs={'class':'form-control'}))
    category = forms.ModelChoiceField(Category.objects.all(), label='類別', widget=forms.Select(attrs={'class':'form-control'}))
    description = forms.CharField(label='細節', widget=forms.Textarea(attrs={'class': 'tinymceTextarea'}))
    price = forms.IntegerField(label='價錢', widget=forms.NumberInput(attrs={'class':'form-control'}))

    class Meta:
        model = Item
        fields = ('name', 'category', 'description', 'price', )

store/views.py
<<<<<<< HEAD
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.urls import reverse

from store.forms import CategoryForm, ItemForm
from store.models import Category, Item


def category(request):
    categorys = Category.objects.all()
    return render(request, 'store/category.html', {'categorys': categorys})


def categoryRead(request, id):
    category = get_object_or_404(Category, id=id)
    return render(request, 'store/categoryRead.html', {'category': category})


def categoryCreate(request):
    if request.method == 'GET':
        categoryForm = CategoryForm()
        return render(request, 'store/categoryCreate.html', {'categoryForm': categoryForm})
    elif request.method == 'POST':
        categoryForm = CategoryForm(request.POST)
        if not categoryForm.is_valid():
            return render(request, 'store/categoryCreate.html', {'categoryForm': categoryForm})

        categoryForm.save()
        messages.success(request, '新增成功')
        return redirect(reverse('store:category'))


def categoryUpdate(request, id):
    category = get_object_or_404(Category, id=id)
    if request.method == 'GET':
        categoryForm = CategoryForm(instance=category)
        return render(request, 'store/categoryUpdate.html', {'categoryForm': categoryForm})
    elif request.method == 'POST':
        categoryForm = CategoryForm(request.POST, instance=category)
        if not categoryForm.is_valid():
            return render(request, 'store/categoryUpdate.html', {'categoryForm': categoryForm})

        categoryForm.save()
        messages.success(request, '修改成功')
        return redirect(reverse('store:category'))


def categoryDelete(request, id):
    category = get_object_or_404(Category, id=id)
    if request.method == 'POST':
        category.delete()
        messages.success(request, '刪除成功')
    return redirect(reverse('store:category'))


def itemCreate(request):
    if request.method == 'GET':
        itemForm = ItemForm()
        return render(request, 'store/itemCreate.html', {'itemForm': itemForm})
    elif request.method == 'POST':
        itemForm = ItemForm(request.POST)
        if not itemForm.is_valid():
            return render(request, 'store/itemCreate.html', {'itemForm': itemForm})

        itemForm.save()
        messages.success(request, '新增成功')
        return redirect(reverse('store:category'))

def itemRead(request, id):
    item = get_object_or_404(Item, id=id)
    return render(request, 'store/itemRead.html', {'item': item})
=======
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.urls import reverse

from store.forms import CategoryForm, ItemForm
from store.models import Category, Item


def category(request):

    categorys = Category.objects.all().order_by('id')
    paginator = Paginator(categorys, 10)
    page = request.GET.get('page')
    categorys = paginator.get_page(page)
    return render(request, 'store/category.html', {'categorys': categorys})


def categoryRead(request, id):
    category = get_object_or_404(Category, id=id)
    return render(request, 'store/categoryRead.html', {'category': category})


@login_required
def categoryCreate(request):
    if request.method == 'GET':
        categoryForm = CategoryForm()
        return render(request, 'store/categoryCreate.html', {'categoryForm': categoryForm})
    elif request.method == 'POST':
        categoryForm = CategoryForm(request.POST)
        if not categoryForm.is_valid():
            return render(request, 'store/categoryCreate.html', {'categoryForm': categoryForm})

        categoryForm.save()
        messages.success(request, '新增成功')
        return redirect(reverse('store:category'))


@login_required
def categoryUpdate(request, id):
    category = get_object_or_404(Category, id=id)
    if request.method == 'GET':
        categoryForm = CategoryForm(instance=category)
        return render(request, 'store/categoryUpdate.html', {'categoryForm': categoryForm})
    elif request.method == 'POST':
        categoryForm = CategoryForm(request.POST, instance=category)
        if not categoryForm.is_valid():
            return render(request, 'store/categoryUpdate.html', {'categoryForm': categoryForm})

        categoryForm.save()
        messages.success(request, '修改成功')
        return redirect(reverse('store:category'))


@login_required
def categoryDelete(request, id):
    category = get_object_or_404(Category, id=id)
    if request.method == 'POST':
        category.delete()
        messages.success(request, '刪除成功')
    return redirect(reverse('store:category'))


@login_required
def itemCreate(request):
    if request.method == 'GET':
        itemForm = ItemForm()
        return render(request, 'store/itemCreate.html', {'itemForm': itemForm})
    elif request.method == 'POST':
        itemForm = ItemForm(request.POST)
        if not itemForm.is_valid():
            return render(request, 'store/itemCreate.html', {'itemForm': itemForm})

        itemForm.save()
        messages.success(request, '新增成功')
        return redirect(reverse('store:category'))


def itemRead(request, id):
    item = get_object_or_404(Item, id=id)
    return render(request, 'store/itemRead.html', {'item': item})
>>>>>>> 2c0e25ea74f3e590d8571b3310da09d326f30201

store/templates/store/category.html
<<<<<<< HEAD
{% extends 'main/base.html' %}
{% block content %}
  <a href="{% url 'store:categoryCreate' %}">新增類別</a>
  <a href="{% url 'store:itemCreate' %}">新增商品</a>
  <table>
    <tr>
      <th>類別</th>
    </tr>
    {% for category in categorys %}
      <tr>
        <td><a href="{% url 'store:categoryRead' category.id %}">{{ category.name }}</a></td>
        <td><a href="{% url 'store:categoryUpdate' category.id %}"><button>修改</button></a></td>
        <td>
          <form method="post" action="{% url 'store:categoryDelete' category.id %}">
            {% csrf_token %}
            <a href="{% url 'store:categoryDelete' category.id %}">
              <input type="submit" value="刪除">
            </a>
          </form>
        </td>
      </tr>
    {% endfor %}
  </table>
=======
{% extends 'main/base.html' %}
{% block content %}
  {% if user.is_authenticated %}
    <a href="{% url 'store:categoryCreate' %}">新增類別</a>
    <a href="{% url 'store:itemCreate' %}">新增商品</a>
  {% endif %}
  <table>
    <tr>
      <th>類別</th>
    </tr>
    {% for category in categorys %}
      <tr>
        <td><a href="{% url 'store:categoryRead' category.id %}">{{ category.name }}</a></td>
        <td><a href="{% url 'store:categoryUpdate' category.id %}">
          <button>修改</button>
        </a></td>
        <td>
          <form method="post" action="{% url 'store:categoryDelete' category.id %}">
            {% csrf_token %}
            <a href="{% url 'store:categoryDelete' category.id %}">
              <input type="submit" value="刪除">
            </a>
          </form>
        </td>
      </tr>
    {% endfor %}
  </table>



{#  <div class="pagination">#}
{#    <span class="step-links">#}
{#        {% if categorys.has_previous %}#}
{#          <a href="?page=1">&laquo; first</a>#}
{#          <a href="?page={{ categorys.previous_page_number }}">previous</a>#}
{#        {% endif %}#}
{##}
{#      <span class="current">#}
{#            Page {{ categorys.number }} of {{ categorys.paginator.num_pages }}.#}
{#        </span>#}
{##}
{#      {% if categorys.has_next %}#}
{#        <a href="?page={{ categorys.next_page_number }}">next</a>#}
{#        <a href="?page={{ categorys.paginator.num_pages }}">last &raquo;</a>#}
{#      {% endif %}#}
{#    </span>#}
{#  </div>#}

  <ul class="pagination">
    {% if categorys.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page=1">&laquo; first</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ categorys.previous_page_number }}">previous</a>
      </li>
    {% endif %}

    {% for i in categorys.paginator.page_range %}
      <li class="page-item {% if i == categorys.number %} active{% endif %}">
        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
      </li>
    {% endfor %}

    {% if categorys.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ categorys.next_page_number }}">next</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ categorys.paginator.num_pages }}">last &raquo;</a>
      </li>
    {% endif %}

  </ul>
>>>>>>> 2c0e25ea74f3e590d8571b3310da09d326f30201
{% endblock %}

store/templates/store/categoryCreate.html
{% extends 'main/base.html' %}
{% block content %}

  <h3>新增類別</h3>
  <form method="post" action="{% url 'store:categoryCreate' %}">
    {% csrf_token %}
    {{ categoryForm.as_p }}
    <input type="submit" value="儲存">
  </form>

{% endblock %}

store/templates/store/categoryRead.html
{% extends 'main/base.html' %}
{% block content %}
  {% if category %}
    <div>
      <div>
        類別: {{ category.name }}
      </div>
      <div>
        {% if category.item_set.all %}
          <table>
            <tr>
              <th>名稱</th>
              <th>價錢</th>
            </tr>
            {% for item in category.item_set.all %}
              <tr>
                <td><a href="{% url 'store:itemRead' item.id %}">{{ item.name }}</a></td>
                <td>{{ item.price }}</td>
              </tr>
            {% endfor %}
          </table>
        {% endif %}
      </div>
    </div>
  {% endif %}
{% endblock %}

store/templates/store/categoryUpdate.html
{% extends 'main/base.html' %}
{% block content %}

  <h3>修改類別</h3>
  <form method="post" action="{% url 'store:categoryUpdate' categoryForm.instance.id %}">
    {% csrf_token %}
    {{ categoryForm.as_p }}

    <input type="submit" value="儲存">
  </form>

{% endblock %}

store/templates/store/itemCreate.html
{% extends 'main/base.html' %}

{% block content %}

  <h3>新增項目</h3>
  <form method="post" action="{% url 'store:itemCreate' %}">
    {% csrf_token %}
    {% for field in itemForm %}
      <div class="form-group">
        {{ field.label_tag }}
        {{ field }}
        {{ field.errors }}
      </div>
    {% endfor %}


    <input type="submit" class="btn btn-primary" value="儲存">
  </form>

{% endblock %}

store/templates/store/itemRead.html
{% extends 'main/base.html' %}

{% block content %}

  {% if item %}
    <p>{{ item.category.name }}</p>
    <p>{{ item.name }}</p>
    <p>{{ item.description|safe }}</p>
  {% endif %}

{% endblock %}