main/urls.py
from django.urls import path, re_path

from main import views

app_name = 'main'
urlpatterns = [
    path('', views.main, name='main')
    # re_path('^.*', views.main, name='main')
]

shop/urls.py
<<<<<<< HEAD
"""shop URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
    # path('main/', include('main.urls')),
    path('', include('main.urls')),

    # re_path('^.*', include('main.urls'))
]
=======
"""shop URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
    path('userAuth/', include('userAuth.urls')),
    # path('main/', include('main.urls')),
    path('', include('main.urls')),

    # re_path('^.*', include('main.urls'))
]
>>>>>>> 2c0e25ea74f3e590d8571b3310da09d326f30201

store/urls.py
from django.urls import path

from store import views


app_name = 'store'
urlpatterns = [
    path('category/', views.category, name='category'),
    path('categoryCreate/', views.categoryCreate, name='categoryCreate'),
    path('categoryRead/<int:id>/', views.categoryRead, name='categoryRead'),
    path('categoryUpdate/<int:id>/', views.categoryUpdate, name='categoryUpdate'),
    path('categoryDelete/<int:id>/', views.categoryDelete, name='categoryDelete'),

    path('itemCreate/', views.itemCreate, name='itemCreate'),
    path('itemRead/<int:id>/', views.itemRead, name='itemRead'),

]

userAuth/urls.py
from django.urls import path

from userAuth import views

app_name = 'userAuth'
urlpatterns = [
    path('userLogin/', views.userLogin, name='userLogin'),
    path('userLogout/', views.userLogout, name='userLogout'),
    path('register/', views.register, name='register')
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render


# Create your views here.
def main(request):
    return render(request, 'main/main.html')

main/templates/main/base.html
<<<<<<< HEAD
{% load static %}
<!doctype html>
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css"
        integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
  {#<link rel="stylesheet" href="{% static 'main/css/main.css' %}">#}
</head>
<body>

{% include 'main/nav.html' %}
{% if messages %}
  <div>
    {% for message in messages %}
      <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
  </div>
{% endif %}

<div class="container">
<div class="row">
<div class="col">
{% block content %}

{% endblock %}
</div>
</div>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js"
        integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4"
        crossorigin="anonymous"></script>
<script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
<script src="{% static 'main/js/main.js' %}"></script>
</body>
=======
{% load static %}
<!doctype html>
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css"
        integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
  {#<link rel="stylesheet" href="{% static 'main/css/main.css' %}">#}
</head>
<body>

{% include 'main/nav.html' %}


<div class="container">
  <div class="row">
    <div class="col">
      {% if messages %}
        <div>
          {% for message in messages %}
            <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
          {% endfor %}
        </div>
      {% endif %}
      <br>
      {% block content %}

      {% endblock %}
    </div>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js"
        integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4"
        crossorigin="anonymous"></script>
<script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
<script src="{% static 'main/js/main.js' %}"></script>
</body>
>>>>>>> 2c0e25ea74f3e590d8571b3310da09d326f30201
</html>

main/templates/main/main.html
{% extends 'main/base.html' %}
{% block content %}
Hello world!
{% endblock %}

main/templates/main/nav.html
<<<<<<< HEAD
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'main:main' %}">首頁</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'store:category' %}">商品 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>

  </div>
=======
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'main:main' %}">首頁</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      {% if not user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'userAuth:userLogin' %}">登入</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'userAuth:register' %}">註冊</a>
        </li>
      {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'userAuth:userLogout' %}">登出</a>
        </li>
      {% endif %}

      <li class="nav-item active">
        <a class="nav-link" href="{% url 'store:category' %}">商品 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>

  </div>
>>>>>>> 2c0e25ea74f3e590d8571b3310da09d326f30201
</nav>